version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "9190:9190"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
