apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: esig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: nascimentomicherenio/esigk8s-jenkins-tomcat:latest 
          ports:
            - containerPort: 9190
          env:
            - name: JAVA_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=jenkins"
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          command: ["sh", "-c", "java -jar /usr/local/tomcat/webapps/jenkins.war --httpPort=9190"]
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
